Semillero_ProgramacioFinal/Models/Sesion/AcademiaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class AcademiaViewModel
    {
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(4)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
    }
}

Semillero_ProgramacioFinal/Models/Sesion/CompetenciaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class CompetenciaViewModel
    {
        public int idcompetencia { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
       // [Required]
       // [Display(Name = "Cupos")]
        public int? cupos { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha competencia")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechacompetencia { get; set; }
        [Required]
        [DataType(DataType.Time)]
        [Display(Name = "Hora inicio")]
       // [DisplayFormat(DataFormatString = "{0:hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> horainicio { get; set; }
        [Required]
        [DataType(DataType.Time)]
        [Display(Name = "Hora final")]
        //[DisplayFormat(DataFormatString = "{0:hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> horafin { get; set; }
        [Required]
        [Display(Name = "Cantidad ejercicios")]
        public int? cantidadejercicios { get; set; }
        [Display(Name = "Numero participantes")]
        [Required]
        public int? numeroparticipantes { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Fecha limite inscripcion")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public Nullable<System.DateTime> limiteinscripcion { get; set; }
        public int? fkestado { get; set; }

 
      
    }
    
}

Semillero_ProgramacioFinal/Models/Sesion/CorreoConfirmacionViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class CorreoConfirmacionViewModels
    {
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(4)]
        [Display(Name = "Asunto")]
        public string asunto { get; set; }
        [Required]
        [StringLength(8000)]
        [MinLength(4)]
        [Display(Name = "Mensaje")]
        public string mensaje { get; set; }
        public int? fkidcompetencia{ get; set; }
    }
}

Semillero_ProgramacioFinal/Models/Sesion/CorreoMasivoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class CorreoMasivoViewModel
    {
        public int? id { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(4)]

        [Display(Name = "Asunto")]
        public string asunto { get; set; }
        [Required]
        [StringLength(8000)]
        [MinLength(4)]
        [Display(Name = "Mensaje")]
        public string mensaje { get; set; }
        
    }
}

Semillero_ProgramacioFinal/Models/Sesion/DocumentoEquipoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class DocumentoEquipoViewModel
    {
        public int fkidcompetencia { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Documento primer participante")]

        public int documento1 { get; set; }


        [Required]
  
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Documento segundo participante")]

        public int documento2 { get; set; }
    }
}

Semillero_ProgramacioFinal/Models/Sesion/DocumentoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class DocumentoViewModel
    {
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(4)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
    }
}

Semillero_ProgramacioFinal/Models/Sesion/EqViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class EqViewModel
    {
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(4)]
        [Display(Name = "Nombre equipo")]
        public string nombre { get; set; }
       
      
 
        public string usuario { get; set; }
        public string contrasena { get; set; }

        public int? fkidcompetencia { get; set; }
        public int? fkidnivel { get; set; }
        public int? fkidestado { get; set; }
    }
}

Semillero_ProgramacioFinal/Models/Sesion/EquipoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class EquipoViewModel
    {
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(4)]
        [Display(Name = "Nombre equipo")]
        public string nombre { get; set; }
        //[Required]
        //[StringLength(15)]
        //[MinLength(7)]
        //[DataType(DataType.PhoneNumber)]
        //[Display(Name = "Documento primer participante")]
        //public string documento1 { get; set; }

        //[Required]
        //[StringLength(15)]
        //[MinLength(7)]
        //[DataType(DataType.PhoneNumber)]
        //[Display(Name = "Documento segunda participante")]

        //public string documento2 { get; set; }

        public string nombredocumento2 { get; set; }
        public string nombredocumento1 { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }

        public int fkidcompetencia { get; set; }
        public int fkidnivel { get; set; }
        public int fkidestado { get; set; }
    }
}

Semillero_ProgramacioFinal/Models/Sesion/MenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class MenuViewModel
    {
        
        public int? id { get; set; }
        public int? fkmenu { get; set; }
        public string nombre { get; set; }

        public string ruta { get; set; }


    }
}

Semillero_ProgramacioFinal/Models/Sesion/RolViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Semillero_ProgramacioFinal.Models.Sesion
{
    public class RolViewModel
    {
        public int idrol { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(4)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        public int? fkestado { get; set; }
    }
}

Semillero_ProgramacioFinal/Controllers/SesionController.cs
using Semillero_ProgramacioFinal.Filters;
using Semillero_ProgramacioFinal.Models;
using Semillero_ProgramacioFinal.Models.ViewModels;
using Semillero_ProgramacioFinal.Models.Sesion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Net.Mail;
using OfficeOpenXml;




namespace Semillero_ProgramacioFinal.Controllers
{
 
    public class SesionController : Controller
    {
         
        // GET: Sesion
        public ActionResult SesionAdmin()
        {
            menu();//En todos los Action que tengan vista
            obtenerDatosUsuario();
            return View( );
        }
        public ActionResult Salir()
        {
            menu();
            Session["User"] = null;
            Session["Persona"] = null;
            Session["User"] = null;
            Session["Persona"] =null;
            Session["Rol"] = null;
            Session["Fkrol"] =null;
            Session["identificacion"] = null;
            Session["idusuario"] = null;
            Session["idc"] = null;
            Session["msm"] = null;
            Session["fkc"] = null;
            Session["competencia"] = null;
            Session["d1"] = null;
            Session["d2"] = null;
            Session["com"] = null;
            Session["eq"] = null;
            return RedirectToAction("Login", "Home");
        }
        public void obtenerDatosUsuario()
        {
            ViewBag.fkrol = Session["Fkrol"];
            int? fkrol = ViewBag.fkrol;
            List<Models.ViewModels.PrivilegioViewModels> privilegio = null;
            using (plataformaEntities bd = new plataformaEntities())
            {
                privilegio = (from d in bd.privilegio
                              where d.fkrol == fkrol && d.fkestadoprivilegio == 1
                              select new PrivilegioViewModels
                              {
                                  idprivilegio = d.idprivilegio,
                                  fkrol = d.fkrol,
                                  fkmenu = d.fkmenu

                              }).ToList();
            }

            ViewBag.privilegio = privilegio;
            ViewBag.nombreApellido = Session["Persona"];
            ViewBag.rol = Session["Rol"];
            ViewBag.identificacion = Session["identificacion"];
            ViewBag.idu = Session["idusuario"];
            ViewBag.plataforma = Session["plataforma"];

        }
        //[AuthorizeUser(idOperacion: 3)]
        public void menu()
        {

            try
            {
                int idr = (int)Session["Fkrol"];
                List<Models.Sesion.MenuViewModel> l = null;
                using (plataformaEntities bd = new plataformaEntities())
                {
                    l = (from m in bd.menu
                         join p in bd.privilegio on m.idmenu equals p.fkmenu
                         join r in bd.rol on p.fkrol equals r.idrol
                         where r.idrol==idr && p.fkestadoprivilegio==1
                         select new Models.Sesion.MenuViewModel
                         {
                             fkmenu=m.fkmenu,
                             id=m.idmenu,
                             nombre=m.nombre,
                             ruta=m.ruta   
                         }

                        ).ToList();
                   

                }

                ViewBag.menu = l;
            }
            catch (Exception ex)
            {

                ViewBag.error = ex;
            }

            
        }
        public ActionResult error404()
        {
            obtenerDatosUsuario();
            menu();
            return View();
        }
        ///////////////////////////// INICIO ROLES Y PERMISOS ////////////////////////////
        [AuthorizeUser(idOperacion: 7)]
        public ActionResult rolesPermisos()
        {
            menu();
            obtenerDatosUsuario();
            List<Models.Sesion.RolViewModels> l = null;
            using (plataformaEntities bd=new plataformaEntities())
            {
                l = (from a in bd.rol
                     select new Models.Sesion.RolViewModels
                     {
                         nombre=a.nombre,
                         id=a.idrol,
                         fkestado=a.fkestadorol
                     }

                    ).ToList();
            }
            ViewBag.rol = l;
            var msm = (string)Session["msm"];
            if (msm!="" && msm!=null)
            {
                ViewBag.error = msm;
                Session["msm"] = null;
            }
                return View();
        }
        [AuthorizeUser(idOperacion: 7)]
        [HttpGet]
        public ActionResult eliminarRol(int id)
        {
            menu();
            obtenerDatosUsuario();
            using (plataformaEntities bd=new plataformaEntities())
            {
               
             var  contador = (from u in bd.usuario
                               where u.fkrol==id
                               select u
                            ).FirstOrDefault();
                if (contador==null)
                {
                     
                var rol = bd.rol.Find(id);
                bd.rol.Remove(rol);
                bd.SaveChanges();
                }
                else
                {
                    Session["msm"] = "No se puede eliminar porque esta en uso";         
                }

             
            }


                return Redirect("~/Sesion/rolesPermisos");
        }


        //public ActionResult editarRol(int id)
        //{
        //    menu();
        //    obtenerDatosUsuario();
        //    RolViewModels model = new RolViewModels();
        //    List<Models.Sesion.MenuViewModel> l = null;
        //    int idr = (int)Session["Fkrol"];
        //    using (plataformaEntities bd = new plataformaEntities())
        //    {
        //        var rol = bd.rol.Find(id);
        //        model.nombre = rol.nombre;

        //        l = (from m in bd.menu
        //             join p in bd.privilegio on m.idmenu equals p.fkmenu
        //             join r in bd.rol on p.fkrol equals r.idrol
        //             where r.idrol == idr && p.fkestadoprivilegio == 1
        //             select new Models.Sesion.MenuViewModel
        //             {
        //                 fkmenu = m.fkmenu,
        //                 id = m.idmenu,
        //                 nombre = m.nombre,
        //                 ruta = m.ruta
        //             }

        //           ).ToList();

        //    }
        //    ViewBag.menu = l;
        //    return View(model);
        //}
        [AuthorizeUser(idOperacion: 7)]
        public ActionResult editarRol(int id)
        {
            menu();
            obtenerDatosUsuario();
            RolViewModels model = new RolViewModels();
            using (plataformaEntities bd =new plataformaEntities())
            {
                var t = bd.rol.Find(id);
                model.fkestado = t.fkestadorol;
                model.nombre = t.nombre;
                model.id = t.idrol;
            }
                return View(model);
        }
        [AuthorizeUser(idOperacion: 7)]
        [HttpPost]
        public ActionResult editarRol(RolViewModels model)
        {
            menu();
            obtenerDatosUsuario();
            if (ModelState.IsValid)
            {
                using (plataformaEntities bd = new plataformaEntities())
                {
                    var tabla = bd.rol.Find(model.id);
                    tabla.nombre = model.nombre;
                    bd.Entry(tabla).State = System.Data.Entity.EntityState.Modified;
                    bd.SaveChanges();
                     
                }

            }
            else
            {

                return View(model);
            }
            return Redirect("~/Sesion/rolesPermisos");
        }
        [AuthorizeUser(idOperacion: 7)]
        public ActionResult agregarRol()
        {
            menu();
            obtenerDatosUsuario();
            return View();
        }
        [AuthorizeUser(idOperacion: 7)]
        [HttpPost]
        public ActionResult agregarRol(RolViewModels model)
        {
            menu();
            obtenerDatosUsuario();
            try
            {
                if (ModelState.IsValid)
                {
                    using (plataformaEntities bd=new plataformaEntities())
                    {
                        var tabla = new rol();
                        tabla.nombre = model.nombre;
                        tabla.fkestadorol = 1;
                        //tabla.fkestado = int.Parse(Request.Form["estadocompetencia"]);
                        bd.rol.Add(tabla);
                        bd.SaveChanges();
                    }

                    return Redirect("~/Sesion/rolesPermisos");
                }
                else
                {
                     return View(model);
                }
              
            }
            catch (Exception e)
            {
                ViewBag.error = e;
                return Redirect("~/Sesion/error404");
            }
           
        }
        [AuthorizeUser(idOperacion: 7)]
        public ActionResult gestionarPrivilegios()
        {

            return View();
        }

        ///////////////////////////// FIN ROLES Y PERMISOS ////////////////////////////

        ///////////////////////////// INICION PLATAFORMA ////////////////////////////
        [AuthorizeUser(idOperacion: 8)]
        public ActionResult gestionarPlataforma()
        {
            obtenerDatosUsuario();
            menu();
            PlataformaViewModel model = new PlataformaViewModel();
            try
            {
               
                using (plataformaEntities bd = new plataformaEntities())

Semillero_ProgramacioFinal/Views/Sesion/agregarCompetencia.cshtml
@model Semillero_ProgramacioFinal.Models.Sesion.CompetenciaViewModel

@{
    ViewBag.Title = "agregarCompetencia";
    Layout = "~/Views/Shared/_LayoutSesion.cshtml";
}

 



<div class="box container">
    <div class="box-header with-border">
 
        <h3 class="box-title">Agregar competencia</h3>
    </div>

 
    <!-- /.box-header -->
    <div class="">

        @using (Html.BeginForm("agregarCompetencia","Sesion",FormMethod.Post))
        {
          

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @*<div class="col-md-5">
                    <div class="form-group">
                        @Html.LabelFor(model => model.cupos, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cupos, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cupos, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@
            </div>
            <div class="row">
                <div class="col col-md-6">
                    <div class="form-group  ">
                        @Html.LabelFor(model => model.fechacompetencia, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.fechacompetencia, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fechacompetencia, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col col-md-3 ">
                    <div class="form-group">
                        @Html.LabelFor(model => model.horainicio, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.horainicio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.horainicio, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col col-md-3 ">
                    <div class="form-group">
                        @Html.LabelFor(model => model.horafin, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.horafin, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.horafin, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.limiteinscripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.limiteinscripcion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.limiteinscripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.cantidadejercicios, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.cantidadejercicios, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cantidadejercicios, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.numeroparticipantes, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.numeroparticipantes, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.numeroparticipantes, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="col col-md-4">
                    <div class="form-group">
                   

                             
                        <select name="estadocompetencia" id="estado" class="col col-md-3 form-control" required>
                            <option selected disabled value="">Estado competencia</option>
                            @foreach (var it in ViewBag.estadoCompetencia)
                            {
                                <option value=@it.id>@it.nombre</option>
                            }
                        </select>
                        
                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-5 col-md-5">
                    <input type="submit" value="Enviar" class="btn btn-primary" />
                </div>
            </div>
        </div>
        }

    </div>

</div>

Semillero_ProgramacioFinal/Views/Sesion/agregarSala.cshtml
@model Semillero_ProgramacioFinal.Models.Sesion.SalaViewModel

@{
    ViewBag.Title = "agregarSala";
    Layout = "~/Views/Shared/_LayoutSesion.cshtml";
}

<div class="box container">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar sala</h3>
    </div>


    <!-- /.box-header -->
    <div class=" ">
        @using (Html.BeginForm("agregarSala", "Sesion", FormMethod.Post))
        {


            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="row">
                    <div class="form-group col col-sm-6">
                        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group col col-sm-4">
                        @Html.LabelFor(model => model.cupos, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.cupos, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cupos, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col col-sm-2">
                            <select name="estado" id="estadoc" class="  form-control" required>
                                <option selected disabled value="">Estado sala</option>
                                @foreach (var it in ViewBag.estado)
                                {
                                    <option value=@it.id>@it.nombre</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-5 col-md-10">
                    <input type="submit" value="Enviar" class="btn btn-primary" />
                </div>
            </div>
            <hr />
            <hr />
        }

    </div>
</div>

 

Semillero_ProgramacioFinal/Views/Sesion/editarAcademia.cshtml
@model Semillero_ProgramacioFinal.Models.Sesion.AcademiaViewModel

@{
    ViewBag.Title = "editarAcademia";
    Layout = "~/Views/Shared/_LayoutSesion.cshtml";
}


<div class="box container">
    <div class="box-header with-border">
        <h3 class="box-title">Editar academia</h3>
    </div>


    <!-- /.box-header -->
    <div class=" ">
        @using (Html.BeginForm("editarAcademia", "Sesion", FormMethod.Post))
        {

            @Html.HiddenFor(model => model.id);
            <div class="form-horizontal">
               
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.id)

                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Semillero_ProgramacioFinal/Views/Sesion/editarCorreoConfirmacion.cshtml
@model Semillero_ProgramacioFinal.Models.Sesion.CorreoConfirmacionViewModels

@{
    ViewBag.Title = "editarCorreoConfirmacion";
    Layout = "~/Views/Shared/_LayoutSesion.cshtml";
}

 






<style>
    .t {
        width: 100%;
        height: 200px;
        font-size: 14px;
        line-height: 18px;
        border: 1px solid #dddddd;
        padding: 10px;
    }
</style>


<div class="box">
    <div class="box-header">
        <h3 class="box-title">
            Editar correo de confirmacion

        </h3>
        <!-- tools box -->
        <div class="pull-right box-tools">
            <button type="button" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-default btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
        <!-- /. tools -->
    </div>
    <!-- /.box-header -->
    <div class="box-body pad">




        @using (Html.BeginForm("editarCorreoConfirmacion", "Sesion", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.id)


                @Html.LabelFor(model => model.asunto, htmlAttributes: new { @class = "" })

                @Html.TextAreaFor(model => model.asunto, htmlAttributes: new { @class = "textarea t" })
                @Html.ValidationMessageFor(model => model.asunto, "", new { @class = "text-danger" })



                @Html.LabelFor(model => model.mensaje, htmlAttributes: new { @class = " " })

                @Html.TextAreaFor(model => model.mensaje, htmlAttributes: new { @class = "textarea t" })
                @Html.ValidationMessageFor(model => model.mensaje, "", new { @class = "text-danger" })


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }



    </div>
     
</div>